[package]
name = "galaxy_engine_build"
version.workspace = true
edition.workspace = true

[features]
default = []
packaged = []

[dependencies]
galaxy_engine_utils = { path = "../galaxy_engine_utils" }
glob.workspace = true
serde = { workspace = true, features = ["derive"] }
image = "0.23.5"
normal-heights = "0.1.2"
sha3 = "0.10.8"