[package]
name = "galaxy_engine_build"
version.workspace = true
edition.workspace = true

[features]
default = []
packaged = []

[dependencies]
galaxy_engine_config = { path = "../galaxy_engine_config", features = ["ron"] }
glob.workspace = true
serde = { workspace = true, features = ["derive"] }
const_format = { workspace = true, features = ["rust_1_64"] }
image = "0.23.5"
normal-heights = "0.1.2"
sha3 = "0.10.0"
bincode.workspace = true
slang = { git = "https://github.com/FloatyMonkey/slang-rs.git" }
