[workspace]
resolver = "2"

members = [
    "galaxy_engine",
    "galaxy_engine_build",
    "gravity_game",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"

[profile.dev]
#opt-level = 1

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[profile.release-with-symbols]
inherits = "release"
lto = false
debug = true
strip = false
