[workspace]
resolver = "2"

members = [
    "galaxy_engine",
    "galaxy_engine_build",
    "galaxy_engine_config",
    "gravity_game",
]
exclude = ["crates/basis-universal-rs"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"

[workspace.dependencies]
ash = { version = "0.38.0", default-features = false, features = ["loaded"] }
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
winit = "0.30.5"
bitflags = "2.6.0"
log = "0.4.0"
thiserror = "2.0.0"
anyhow = "1.0.0"
bytemuck = "1.19.0"
arrayvec = "0.7.6"
itertools = "0.13.0"
#fastrand = "2.1.1"
serde = "1.0.214"
ultraviolet = "0.9.2"
glob = "0.3.1"
enum_delegate = "0.2.0"
shipyard = "0.7.4"
ron = "0.8.1"
zstd = "0.13"
ktx2 = { git = "https://github.com/BVE-Reborn/ktx2.git" }
const_format = "0.2.33"

[profile.dev]
#opt-level = 1

[profile.dev.package."basis-universal-sys"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[profile.release-with-symbols]
inherits = "release"
lto = false
debug = true
strip = false
