[package]
name = "galaxy_engine"
version.workspace = true
edition.workspace = true

[features]
default = []
debug_info = ["ash/debug"]

[dependencies]
ash = { workspace = true, default-features = false, features = ["loaded"] }
ash-window.workspace = true
raw-window-handle.workspace = true
winit.workspace = true
bitflags.workspace = true
log.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
arrayvec.workspace = true
itertools.workspace = true
fastrand.workspace = true
ultraviolet.workspace = true
gpu-allocator = { version = "0.27.0", default-features = false, features = ["vulkan"] }
presser = "0.3.1"
obj-rs = "0.7.4"
meshopt = "0.4.0"
ktx2 = "0.3.0"
parking_lot = { version = "0.12.3", default-features = false }
castaway = { version = "0.2.3", default-features = false }
smol_str = "0.3.2"

[build-dependencies]
galaxy_engine_build = { path = "../galaxy_engine_build" }
