[package]
name = "galaxy_engine"
version.workspace = true
edition.workspace = true

[features]
default = []
debug_info = ["ash/debug"]
packaged = ["galaxy_engine_build/packaged"]

[dependencies]
galaxy_engine_config = { path = "../galaxy_engine_config", features = ["ron"] }
ash = { workspace = true, default-features = false, features = ["loaded"] }
ash-window.workspace = true
raw-window-handle.workspace = true
winit.workspace = true
bitflags = { workspace = true, features = ["serde"] }
log.workspace = true
thiserror.workspace = true
anyhow.workspace = true
bytemuck = { workspace = true, features = ["derive", "must_cast", "min_const_generics"] }
arrayvec = { workspace = true, features = ["serde"] }
itertools.workspace = true
#fastrand.workspace = true
ultraviolet = { workspace = true, features = ["bytemuck", "serde"] }
serde = { workspace = true, features = ["derive"] }
gpu-allocator = { version = "0.27.0", default-features = false, features = ["vulkan"] }
presser = "0.3.1"
obj-rs = "0.7.4"
meshopt = "0.4.0"
ktx2.workspace = true
parking_lot = { version = "0.12.3", default-features = false }
castaway = { version = "0.2.3", default-features = false }
glob.workspace = true
const_format = { version = "0.2.33", features = ["rust_1_64"] }
indexmap = { version = "2.6.0", features = ["serde"] }
ron = { workspace = true, features = ["indexmap"] }
#static_assertions = "1.1.0"
shipyard.workspace = true
enum_delegate.workspace = true
zstd.workspace = true
basis-universal = { path = "../crates/basis-universal-rs/basis-universal" }
self_cell = "1.1.0"
path-slash = "0.2.1"
bevy_mikktspace = "0.15.0"

[build-dependencies]
galaxy_engine_build = { path = "../galaxy_engine_build" }
