[package]
name = "galaxy_engine"
version.workspace = true
edition.workspace = true

[features]
default = []
debug_info = ["ash/debug"]

[dependencies]
ash = { version = "0.38.0", default-features = false, features = ["loaded"] }
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
winit = "0.30.5"
bitflags = "2.6.0"
log = "0.4.0"
thiserror = "1.0.64"
nalgebra = { version = "0.33.0", features = ["bytemuck"] }
bytemuck = { version = "1.18.0", features = ["derive", "must_cast"] }
gpu-allocator =  { version = "0.27.0", default-features = false, features = ["vulkan"] }
presser = "0.3.1"
arrayvec = "0.7.6"
itertools = "0.13.0"
obj-rs = "0.7.4"
meshopt = "0.3.0"
ktx2 = "0.3.0"
fastrand = "2.1.1"
parking_lot = { version = "0.12.3", default-features = false }

[build-dependencies]
galaxy_engine_build = { path = "../galaxy_engine_build" }
