[package]
name = "gravity_game"
version = "0.1.0"
edition.workspace = true

[features]
default = []
debug_info = ["galaxy_engine/debug_info"]
packaged = ["galaxy_engine/packaged"]

[dependencies]
galaxy_engine = { path = "../galaxy_engine" }
winit.workspace = true
thiserror.workspace = true
env_logger = { version = "0.11.5", default-features = false, features = ["auto-color"] }
